// Random number generator

#include <iostream>											// Declares objects that control reading from and writing to the standard streams.
#include <random>											// Defines facilities for random number generation, allowing creation of uniformly distributed random numbers.

using namespace std;										// Enables dropping the prefix 'std::', e.g., 'std::default_random_engine generator;' becomes 'default_random_engine generator;'

int main()
{
	// The same set of numbers is generated with every execution of this program!
	// Changing the value of distribution() creates a new fixed set of random numbers.
	// See https://www.cplusplus.com/reference/random/?kw=random for how to change this (search 'seeds').
	cout << "Start random number generation! \n";
	// Generators:		Objects that generate uniformly distributed numbers.
	default_random_engine generator;						// A pseudo-random number engine	(an instantiation of a class).	The default random engine.
	// Distributions:	Objects that transform sequences of numbers generated by a generator into sequences of numbers that follow a specific random variable distribution, such as uniform, normal or binomial.
	//					The distribution parameters, here 1 and 4, are set on construction.
	uniform_int_distribution<int> distribution(1, 4);		// A uniform distribution			(a class template).				A uniform discrete distribution.
	int dice_roll;
	for (int i = 0; i < 20; i++)							// Generate 20 random numbers.
	{
		// Roll the dice! Generate a random number between 1 and 4 inclusive.
		dice_roll = distribution(generator);				// Distribution objects generate random numbers by means of their operator() member, which takes a generator object as argument.
		std::cout << "dice_roll: " << dice_roll << " i: " << i + 1 << "\n";
	}
}